let correctAnswer = [
    "Mount Everest",
    "Paris",
    "206",
    "100°C",
    "The Great Wall of China",
    "Potassium",
    "Leonardo da Vinci",
    "Pride",
    "Yen",
    "One",
    "Paris",
    "Nile",
    "Star",
    "France",
    "South America",
    "Mercury",
    "5",
    "1776",
    "Green",
    "Pacific",
    "299,792,458 m/s",
    "Moon's gravitational pull",
    "Madrid",
    "Au",
    "4",
    "50",
    "Volga",
    "3",
    "Neil Armstrong",
    "Pound",
    "Australia",
    "About 3 pounds",
    "Hawaii",
    "Sahara",
    "118",
    "Mars",
    "32",
    "Canadian Dollar",
    "Jupiter",
    "Brasília",
    "Blue whale",
    "Louvre Museum",
    "Yuan",
    "Venus",
    "1886",
    "Rupee",
    "206",
    "Mercury",
    "Red circle",
    "Canberra",
    "Ostrich",
    "5",
    "Peso",
    "Neptune",
    "Centuries",
    "Ruble",
    "Coast Redwood",
    "Millions",
    "Rand",
    "Saturn",
    "-128.6°F",
    "Swiss Franc",
    "Skin",
    "Real",
    "Uranus",
    "Jericho",
    "Euro",
    "Yes",
    "Euro",
    "No",
    "Olympus Mons",
    "Euro",
    "5",
    "Euro",
    "Rafflesia arnoldii",
    "Yen",
    "Stapes",
    "Dollar",
    "Yuan",
    "Cheetah",
    "Rupee",
    "Yangtze",
    "Canadian Dollar",
    "Sonoran",
    "Australian Dollar",
    "Peregrine falcon",
    "Pound",
    "Mercury",
    "Sailfish",
    "Peso",
    "Bumblebee bat",
    "Rand",
    "Black mamba",
    "Ruble",
    "Lake Baikal",
    "Swiss Franc",
    "Cheetah",
    "Real",
    "Mariana Trench",
    "Euro",
    "Spiny-tailed iguana",
    "Euro",
    "Challenger Deep",
    "Euro",
    "Black marlin",
    "Lake Baikal",
    "Euro",
    "Swordfish",
    "Crater Lake",
    "Yen",
    "Bamboo",
    "Lake Titicaca",
    "Canadian Dollar",
    "Australian tiger beetle",
    "Lake Tanganyika",
    "Mars",
    "Mercury",
    "Jupiter",
    "Saturn",
    "Red Dwarf",
    "Milky Way",
    "Astronomical Unit",
    "Titan",
    "Sirius",
    "Solar Eclipse",
    "Mars",
    "Sun",
    "Jupiter",
    "Uranus",
    "Pluto",
    "Yuri Gagarin",
    "6",
    "Hubble Telescope",
    "Distance",
    "Venus",
    "you",
    "speed",
    "Rick Blaine",
    "home",
    "me?",
    "Terminator",
    "Jack Dawson",
    "chocolates",
    "Paris",
    "tested me. I ate his liver...",
    "but your enemies closer",
    "you're sorry",
    "corner",
    "home",
    "the truth!",
    "another day",
    "beyond!",
    "baby",
    "hello",
    "people",
    "1960s",
    "Coco Chanel",
    "1920s",
    "1970s",
    "1920s",
    "19th Century",
    "Christian Dior",
    "1940s",
    "19th Century",
    "1970s",
    "1960s",
    "Twiggy",
    "Christian Dior",
    "1960s",
    "18th Century",
    "Nylon stockings",
    "India",
    "1970s",
    "Elizabethan Era",
    "Diane von Fürstenberg",
    "Griffin",
    "Dragon",
    "Scotland",
    "Unicorn",
    "Sasquatch",
    "Mermaid",
    "North America",
    "Phoenix",
    "Latin America",
    "Centaur",
    "Irish folklore",
    "Vampire",
    "Disasters",
    "Medusa",
    "Godzilla",
    "Norse mythology",
    "Kong",
    "Japanese folklore",
    "Underworld",
    "Algonquian",
    "Spain",
    "Avocado",
    "Sushi",
    "Beetroot",
    "USA",
    "Feta",
    "Hungary",
    "China",
    "Pizza",
    "Austria",
    "Spain",
    "India",
    "France",
    "England",
    "Turkey",
    "Hummus",
    "Mexico",
    "France",
    "Scotland",
    "Udon",
    "Clark Kent",
    "Tony Stark",
    "Batman",
    "Peter Parker",
    "Diana Prince",
    "Bruce Banner",
    "Natasha Romanoff",
    "Bruce Wayne",
    "Captain America",
    "Logan",
    "Phoenix",
    "Wonder Woman",
    "Barry Allen",
    "Thunder",
    "Black Widow",
    "Thor",
    "Jack Napier",
    "Charles Xavier",
    "Hawkeye",
    "Cyclops",
    "1912",
    "Frank Morris",
    "Orson Welles",
    "Lake Placid",
    "1986",
    "1963",
    "New Jersey",
    "Money",
    "Boston Harbor",
    "Texas",
    "Unidentified",
    "Alexander Selkirk",
    "UFO sighting",
    "Skylab",
    "Vesna Vulović",
    "Portland",
    "USS Cyclops",
    "Mammoths",
    "Asp",
    "Formosus",
    "Queen",
    "The Bodyguard",
    "Michael Jackson",
    "Ludwig",
    "Madonna",
    "Eagles",
    "N.W.A",
    "Trumpet",
    "Bono",
    "Same name",
    "Vivaldi",
    "Adele",
    "John Lennon",
    "Piano",
    "Nicki Minaj",
    "Aaron",
    "Hans Zimmer",
    "Aretha Franklin",
    "Imagine Dragons",
    "Frozen",
    "Alexander Graham Bell",
    "Apple",
    "Uniform Resource Locator",
    "Unimate",
    "Tim Berners-Lee",
    "1982",
    "Google",
    "Charles Babbage",
    "1879",
    "Johannes Gutenberg",
    "17th",
    "Bill Gates",
    "Xerox",
    "1972",
    "Guglielmo Marconi",
    "1927",
    "Karl Benz",
    "C",
    "James Clerk Maxwell",
    "Ford",
    "Ocean Quahog",
    "Starfish",
    "Sailfish",
    "Peacock",
    "Blue Whale",
    "Pygmy Three-toed Sloth",
    "Snail",
    "Bat",
    "Bee Hummingbird",
    "Alpine Swift",
    "Octopus",
    "Clownfish",
    "Basilisk Lizard",
    "Platypus",
    "Owl",
    "Turritopsis dohrnii jellyfish",
    "Pufferfish",
    "Chameleon",
    "Sea Otters",
    "Sperm Whale",
];

let wrongAnswer = [
    "Mount Kilimanjaro",
    "Rome",
    "215",
    "90°C",
    "Berlin Wall",
    "Iron",
    "Vincent van Gogh",
    "Herd",
    "Dollar",
    "Two",
    "London",
    "Amazon",
    "Planet",
    "Spain",
    "Africa",
    "Venus",
    "4",
    "1700",
    "Blue",
    "Atlantic",
    "500,000,000 m/s",
    "Sun's heat",
    "Barcelona",
    "Ag",
    "2",
    "52",
    "Danube",
    "4",
    "Buzz Aldrin",
    "Dollar",
    "New Zealand",
    "About 1.5 pounds",
    "Alaska",
    "Atacama",
    "100",
    "Jupiter",
    "30",
    "Australian Dollar",
    "Saturn",
    "Bogotá",
    "Elephant",
    "The Met",
    "Yen",
    "Mars",
    "1900",
    "Dollar",
    "210",
    "Mars",
    "White stripes",
    "Sydney",
    "Pelican",
    "6",
    "Rupee",
    "Uranus",
    "Decades",
    "Yen",
    "Banyan Tree",
    "Thousands",
    "Peso",
    "Jupiter",
    "-90°F",
    "Dollar",
    "Heart",
    "Peso",
    "Neptune",
    "Rome",
    "Dollar",
    "No",
    "Dollar",
    "Yes",
    "Mauna Loa",
    "Dollar",
    "4",
    "Dollar",
    "Sunflower",
    "Dollar",
    "Malleus",
    "Yen",
    "Dollar",
    "Lion",
    "Dollar",
    "Ganges",
    "Pound",
    "Mojave",
    "Dollar",
    "Golden eagle",
    "Dollar",
    "Venus",
    "Shark",
    "Rupee",
    "Kangaroo rat",
    "Peso",
    "Rattlesnake",
    "Yen",
    "Lake Superior",
    "Pound",
    "Lion",
    "Peso",
    "Bermuda Trench",
    "Dollar",
    "Gecko",
    "Dollar",
    "Mariana Deep",
    "Dollar",
    "Tuna",
    "Lake Superior",
    "Dollar",
    "Dolphin",
    "Lake Tahoe",
    "Dollar",
    "Grass",
    "Lake Michigan",
    "Dollar",
    "Spider",
    "Lake Victoria",
    "Venus",
    "Venus",
    "Earth",
    "Jupiter",
    "Blue Giant",
    "Andromeda",
    "Light Year",
    "Europa",
    "Betelgeuse",
    "Lunar Eclipse",
    "Mercury",
    "Moon",
    "Earth",
    "Mars",
    "Neptune",
    "Neil Armstrong",
    "8",
    "James Webb Telescope",
    "Time",
    "Mars",
    "everyone",
    "flight",
    "Michael Corleone",
    "Kansas",
    "us?",
    "RoboCop",
    "Harry Potter",
    "jellybeans",
    "London",
    "questioned me. I ignored him...",
    "and your family closer",
    "you love them",
    "a closet",
    "mom",
    "me!",
    "a mystery",
    "above!",
    "dude",
    "goodbye",
    "ghosts",
    "1950s",
    "Louis Vuitton",
    "1930s",
    "1960s",
    "1950s",
    "18th Century",
    "Yves Saint Laurent",
    "1950s",
    "20th Century",
    "1980s",
    "1970s",
    "Audrey Hepburn",
    "Yves Saint Laurent",
    "1970s",
    "17th Century",
    "Wool suits",
    "China",
    "1980s",
    "Victorian Era",
    "Coco Chanel",
    "Sphinx",
    "Griffin",
    "Ireland",
    "Pegasus",
    "Yeti",
    "Harpy",
    "Australia",
    "Harpy",
    "North America",
    "Minotaur",
    "Greek mythology",
    "Werewolf",
    "Good fortune",
    "Harpy",
    "Kraken",
    "Greek mythology",
    "Mothman",
    "Chinese folklore",
    "Valhalla",
    "Celtic",
    "Italy",
    "Tomato",
    "Taco",
    "Tomato",
    "Italy",
    "Cheddar",
    "Germany",
    "Japan",
    "Burrito",
    "Germany",
    "Italy",
    "Thailand",
    "Germany",
    "USA",
    "Greece",
    "Falafel",
    "Italy",
    "Belgium",
    "Ireland",
    "Ramen",
    "Bruce Wayne",
    "Steve Rogers",
    "Clark Kent",
    "Bruce Wayne",
    "Selina Kyle",
    "Tony Stark",
    "Wanda Maximoff",
    "Tony Stark",
    "Tony Stark",
    "Scott Summers",
    "Storm",
    "Natasha Romanoff",
    "Wally West",
    "Love",
    "Wanda Maximoff",
    "Hulk",
    "Joe Kerr",
    "Logan",
    "Tony Stark",
    "Wolverine",
    "1911",
    "Al Capone",
    "H.G. Wells",
    "Moscow",
    "1984",
    "1961",
    "Germany",
    "Gold",
    "Thames River",
    "California",
    "Ted Bundy",
    "Ernest Shackleton",
    "Nuclear test",
    "Sputnik",
    "Juliane Koepcke",
    "Seattle",
    "USS Enterprise",
    "Dinosaurs",
    "Scorpion",
    "John XXI",
    "The Beatles",
    "Dirty Dancing",
    "Elvis Presley",
    "Johann",
    "Cyndi Lauper",
    "Rolling Stones",
    "2Pac",
    "Saxophone",
    "Sting",
    "Les Misérables",
    "Bach",
    "Beyoncé",
    "Mick Jagger",
    "Violin",
    "Cardi B",
    "Lee",
    "John Williams",
    "Diana Ross",
    "OneRepublic",
    "Tangled",
    "Thomas Edison",
    "Samsung",
    "Universal Relay Locator",
    "ASIMO",
    "Robert Cailliau",
    "1970",
    "Yahoo",
    "Alan Turing",
    "1815",
    "Benjamin Franklin",
    "18th",
    "Steve Jobs",
    "IBM",
    "1950",
    "Nikola Tesla",
    "1911",
    "Henry Ford",
    "Python",
    "Isaac Newton",
    "General Motors",
    "Elephant",
    "Lizard",
    "Dolphin",
    "Flamingo",
    "Elephant",
    "Human",
    "Shark",
    "Elephant",
    "Ostrich",
    "Eagle",
    "Human",
    "Lion",
    "Cheetah",
    "Kangaroo",
    "Giraffe",
    "Human",
    "Shark",
    "Giraffe",
    "Dolphins",
    "Human",
];



let questionArr = [
    "What is the tallest mountain in the world?",
    "What is the capital of France?",
    "How many bones are there in the human body?",
    "At what temperature does water boil?",
    "What is the longest wall in the world?",
    "What is the main nutrient found in bananas?",
    "Who painted the Mona Lisa?",
    "What is a group of lions called?",
    "What is the currency of Japan?",
    "How many moons does Earth have?",
    "In which city is the Eiffel Tower located?",
    "Which is the longest river in the world?",
    "What is the sun?",
    "Who gifted the Statue of Liberty to the United States?",
    "In which continent is the Amazon Rainforest located?",
    "Which planet is closest to the sun?",
    "How many toes do cats have on their front paws?",
    "In what year was the Declaration of Independence signed?",
    "What color is an emerald?",
    "Which is the largest ocean in the world?",
    "What is the speed of light?",
    "What causes ocean tides?",
    "What is the capital of Spain?",
    "What is the chemical symbol for gold?",
    "How many chambers does the human heart have?",
    "How many states are there in the United States?",
    "Which is the longest river in Europe?",
    "How many sides does a triangle have?",
    "Who was the first person to walk on the moon?",
    "What is the currency of the United Kingdom?",
    "Where is the Great Barrier Reef located?",
    "How much does the human brain weigh?",
    "Which state was the 50th to join the United States?",
    "What is the largest desert in the world?",
    "How many elements are there in the periodic table?",
    "Which planet is often called the Red Planet?",
    "How many teeth does the human body have?",
    "What is the currency of Canada?",
    "Which is the largest planet in our solar system?",
    "What is the capital of Brazil?",
    "What is the largest mammal in the world?",
    "Where is the Mona Lisa displayed?",
    "What is the currency of China?",
    "Which planet is often called Earth's sister planet?",
    "In what year was the Statue of Liberty dedicated?",
    "What is the currency of India?",
    "How many bones are there in the human skeleton?",
    "Which is the smallest planet in our solar system?",
    "What is the design on the flag of Japan?",
    "What is the capital of Australia?",
    "What is the largest bird in the world?",
    "How many senses does the human body have?",
    "What is the currency of Mexico?",
    "Which planet is the eighth from the sun?",
    "How long did it take to build the Great Wall of China?",
    "What is the currency of Russia?",
    "What is the tallest tree in the world?",
    "How many colors can the human eye perceive?",
    "What is the currency of South Africa?",
    "Which planet has beautiful rings?",
    "What is the coldest temperature ever recorded on Earth?",
    "What is the currency of Switzerland?",
    "What is the largest organ in the human body?",
    "What is the currency of Brazil?",
    "Which planet is often called an ice giant?",
    "What is the oldest known city?",
    "What is the currency of Germany?",
    "Can the human liver regenerate itself?",
    "What is the currency of France?",
    "Is Pluto still considered a planet?",
    "What is the largest volcano in our solar system?",
    "What is the currency of Italy?",
    "How many lobes do the human lungs have?",
    "What is the currency of Spain?",
    "What is the largest flower in the world?",
    "What is the currency of Japan?",
    "What is the smallest bone in the human body?",
    "What is the currency of the United States?",
    "What is the currency of China?",
    "What is the fastest land animal?",
    "What is the currency of India?",
    "What is the longest river in Asia?",
    "What is the currency of Canada?",
    "What is the largest desert in North America?",
    "What is the currency of Australia?",
    "What is the fastest bird in level flight?",
    "What is the currency of the United Kingdom?",
    "What is the smallest planet in our solar system?",
    "What is the fastest fish in the ocean?",
    "What is the currency of Mexico?",
    "What is the smallest mammal in the world?",
    "What is the currency of South Africa?",
    "What is the fastest snake in the world?",
    "What is the currency of Russia?",
    "What is the largest freshwater lake in the world?",
    "What is the currency of Switzerland?",
    "What is the fastest land mammal?",
    "What is the currency of Brazil?",
    "What is the deepest ocean trench?",
    "What is the currency of Germany?",
    "What is the fastest land reptile?",
    "What is the currency of France?",
    "What is the deepest part of the ocean?",
    "What is the currency of Italy?",
    "What is the fastest swimmer in the ocean?",
    "What is the deepest freshwater lake in the world?",
    "What is the currency of Spain?",
    "What is the fastest underwater swimmer?",
    "What is the deepest lake in North America?",
    "What is the currency of Japan?",
    "What is the fastest growing plant?",
    "What is the deepest lake in South America?",
    "What is the currency of Canada?",
    "What is the fastest land invertebrate?",
    "What is the deepest lake in Africa?",
    "Name the 'Red Planet'?",
    "Which planet is nearest to the Sun?",
    "Largest planet in our solar system?",
    "Which planet is known for rings?",
    "Most common star type in the Milky Way?",
    "Galaxy that contains Earth?",
    "Unit for distance from Earth to Sun?",
    "Largest moon of Saturn?",
    "Brightest star in the night sky?",
    "What occurs during a Solar Eclipse?",
    "Second smallest planet in our system?",
    "Which celestial body is at our system's center?",
    "Planet with strongest magnetic field?",
    "Which planet tilts on its side in orbit?",
    "Which body was demoted to 'dwarf planet'?",
    "First human to travel into space?",
    "How many planets have moons in our system?",
    "Name the space telescope launched in 1990?",
    "What does a light year measure?",
    "Which planet is Earth's 'sister'?",
    "Complete: 'May the force be with...'?",
    "'I feel the need - the need for...'?",
    "Who said: 'Here's looking at you, kid'?",
    "Complete: 'There's no place like...'?",
    "'You talking to...' what?",
    "Who said: 'I'll be back'?",
    "Who claims: 'I am king of the world!'?",
    "Finish: 'Life is like a box of...'?",
    "Who said: 'We'll always have...'?",
    "Who declared: 'A census taker once...'?",
    "Finish: 'Keep your friends close...'?",
    "'Love means never having to say...'?",
    "Who said: 'Nobody puts Baby in a...'?",
    "Complete: 'E.T. phone...'?",
    "Finish: 'You can't handle...'?",
    "'After all, tomorrow is...'?",
    "Complete: 'To infinity and...'?",
    "Finish: 'Hasta la vista, ...'?",
    "Who said: 'You had me at...'?",
    "Complete: 'I see dead...'?",
    "Which era popularized mini skirts?",
    "Which designer made the little black dress?",
    "Flapper dresses were iconic in which era?",
    "Bell-bottoms are a product of which decade?",
    "Pilgrim collars were popular in which decade?",
    "In which century was the crinoline popular?",
    "Who popularized the pencil skirt?",
    "Which era made zoot suits popular?",
    "Hoop skirts were popular in which century?",
    "Platform shoes were a trend in which decade?",
    "Which decade embraced psychedelic prints?",
    "Who was a fashion icon in the 1960s?",
    "Which designer created the 'New Look'?",
    "Tie-dye was a trend in which decade?",
    "Powdered wigs were popular in which century?",
    "Which fashion item was rationed in WWII?",
    "The Nehru jacket originated in which country?",
    "Punk fashion emerged in which decade?",
    "Ruffled collars were popular in which era?",
    "Who is known for their wrap dress?",
    "Which creature has a lion's body and eagle’s head?",
    "What is the fire-breathing creature in Greek myth?",
    "Loch Ness Monster is said to inhabit where?",
    "Which mythical horse has a single horn?",
    "Bigfoot is also known as?",
    "Which creature is half woman, half fish?",
    "The jackalope is a mythical creature from?",
    "Which bird is known to rise from its ashes?",
    "Chupacabra is a creature primarily sighted in?",
    "Which creature is half man, half horse?",
    "Banshees are considered omens of death in?",
    "Which creature turns to stone in sunlight?",
    "Mothman sightings are associated with?",
    "Which creature has snake hair and turns people to stone?",
    "Which dragon-like creature destroys Tokyo?",
    "Kraken is a giant sea monster from?",
    "Which creature is a giant ape in Japanese mythology?",
    "Kappa is a mythical creature in?",
    "Cerberus guards the gates to?",
    "Wendigo is a mythical creature from which culture?",
    "Which country is Paella originated from?",
    "What is the main ingredient in Guacamole?",
    "Which dish is associated with Japan?",
    "Borscht soup is made primarily of what?",
    "Pasta Primavera was created in what country?",
    "Which cheese is used in a Greek Salad?",
    "Goulash is a traditional dish of which country?",
    "Dim Sum originated from which country?",
    "Which dish is traditionally Italian?",
    "Wiener Schnitzel is a dish from which country?",
    "Which country is the birthplace of Tapas?",
    "Tandoori Chicken is a dish from which country?",
    "Croissant is associated with which country?",
    "Which nation created Fish and Chips?",
    "Baklava is a sweet treat from which country?",
    "Which dish is made from mashed chickpeas?",
    "In which country was the Caesar Salad invented?",
    "Beef Bourguignon is a dish from which country?",
    "Which country is the home of the Haggis?",
    "Which dish consists mainly of thick wheat noodles?",
    "What's the alter ego of Superman?",
    "Who becomes Iron Man?",
    "Bruce Wayne fights crime as whom?",
    "Who swings around NYC as Spider-Man?",
    "Who is also known as Wonder Woman?",
    "Who turns big and green as the Hulk?",
    "Black Widow's real name is what?",
    "Who is the billionaire behind Batman?",
    "Steve Rogers is also known as who?",
    "What is Wolverine’s real name?",
    "Jean Grey is also known as?",
    "What hero is Diana Prince also known as?",
    "Who is the alter ego of the Flash?",
    "Thor is the god of what?",
    "Natasha Romanoff is also known as?",
    "Who wields a magical hammer?",
    "What alias does the Joker often use?",
    "Who is also known as Professor X?",
    "Clint Barton is better known as?",
    "Scott Summers is also known as?",
    "The Titanic sank in which year?",
    "Who escaped Alcatraz in 1962?",
    "Who performed the War of the Worlds radio play?",
    "Where did the Miracle on Ice happen?",
    "When did the Chernobyl disaster occur?",
    "In what year was JFK assassinated?",
    "Where was the Hindenburg disaster?",
    "What was stolen in the Great Train Robbery?",
    "Where did the Boston Tea Party take place?",
    "Which U.S. state was once its own country?",
    "Who was the serial killer in the Zodiac case?",
    "Who survived 227 days at sea in a lifeboat?",
    "What was the Roswell incident about?",
    "Who fell from space in 1979?",
    "Who survived a 16,000 ft fall without a parachute?",
    "Where did DB Cooper hijack a plane?",
    "What ship vanished in the Bermuda Triangle?",
    "What bubbled up in the La Brea Tar Pits?",
    "What animal did Cleopatra use to commit suicide?",
    "Which pope's corpse was put on trial?",
    "Who sang 'Bohemian Rhapsody'?",
    "Which movie features 'I Will Always Love You'?",
    "Who is known as the 'King of Pop'?",
    "What is Beethoven's first name?",
    "Who sang 'Like a Virgin' in the 80s?",
    "Which band performed 'Hotel California'?",
    "Who rapped 'Straight Outta Compton'?",
    "What instrument did Miles Davis play?",
    "Who is the lead vocalist of U2?",
    "Which musical is 'The Phantom of the Opera' from?",
    "Who composed 'The Four Seasons'?",
    "Who sang 'Rolling in the Deep'?",
    "Who is a member of The Beatles?",
    "Which instrument has 88 keys?",
    "Who performed 'Super Bass'?",
    "What is Elvis Presley's middle name?",
    "Who composed the music for 'The Lion King'?",
    "Who sang 'Respect' in 1967?",
    "Which band sings 'Radioactive'?",
    "Which movie features the song 'Let It Go'?",
    "Who invented the telephone?",
    "Which company created the iPhone?",
    "What does 'URL' stand for?",
    "What was the first programmable robot?",
    "Who developed the World Wide Web?",
    "When was the first computer virus released?",
    "Which company developed the search engine Google?",
    "Who is considered the father of the computer?",
    "When was the first electric light bulb invented?",
    "Who invented the printing press?",
    "In which century was the telescope invented?",
    "Who co-founded Microsoft?",
    "Which company produced the first computer mouse?",
    "When was the first video game console released?",
    "Who is credited with inventing the radio?",
    "What year was the first electronic television invented?",
    "Who is credited with inventing the automobile?",
    "Which programming language came first, C or Python?",
    "Who is known for developing the theory of electromagnetism?",
    "Which company was first to implement the assembly line?",
    "Animal with longest lifespan?",
    "Animal that can regrow limbs?",
    "Fastest ocean animal?",
    "Bird known for courtship dance?",
    "Largest mammal in the world?",
    "Animal with 2 beats/minute heartbeat?",
    "Animal with the most teeth?",
    "Only mammal capable of flight?",
    "Smallest bird in the world?",
    "Animal that sleeps while flying?",
    "Animal with three hearts?",
    "Animal that changes its gender?",
    "Animal that runs on water?",
    "Mammal that lays eggs?",
    "Animal that turns head 270 degrees?",
    "Animal capable of biological immortality?",
    "Fish that puffs up to deter predators?",
    "Animal with tongue longer than body?",
    "Mammal that holds hands while sleeping?",
    "Animal with the largest brain?",
];

export { correctAnswer, wrongAnswer, questionArr };