// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBridgeAPI.Data;

#nullable disable

namespace TravelBridgeAPI.Migrations
{
    [DbContext(typeof(FlightLocationsContext))]
    partial class FlightLocationsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("TravelBridgeAPI.Models.FlightModels.FlightLocations.Datum", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .HasColumnType("TEXT");

                    b.Property<string>("cityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .HasColumnType("TEXT");

                    b.Property<string>("countryName")
                        .HasColumnType("TEXT");

                    b.Property<string>("countryNameShort")
                        .HasColumnType("TEXT");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("parent")
                        .HasColumnType("TEXT");

                    b.Property<string>("photoUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("region")
                        .HasColumnType("TEXT");

                    b.Property<string>("regionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .HasColumnType("TEXT");

                    b.HasKey("DataId");

                    b.HasIndex("Keyword", "Language");

                    b.ToTable("Data");
                });

            modelBuilder.Entity("TravelBridgeAPI.Models.FlightModels.FlightLocations.Distancetocity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DatumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("unit")
                        .HasColumnType("TEXT");

                    b.Property<float?>("value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("DatumId")
                        .IsUnique();

                    b.ToTable("DistancesToCity");
                });

            modelBuilder.Entity("TravelBridgeAPI.Models.FlightModels.FlightLocations.Rootobject", b =>
                {
                    b.Property<string>("Keyword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Keyword", "Language");

                    b.ToTable("Rootobjects");
                });

            modelBuilder.Entity("TravelBridgeAPI.Models.FlightModels.FlightLocations.Datum", b =>
                {
                    b.HasOne("TravelBridgeAPI.Models.FlightModels.FlightLocations.Rootobject", "rootobject")
                        .WithMany("data")
                        .HasForeignKey("Keyword", "Language")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rootobject");
                });

            modelBuilder.Entity("TravelBridgeAPI.Models.FlightModels.FlightLocations.Distancetocity", b =>
                {
                    b.HasOne("TravelBridgeAPI.Models.FlightModels.FlightLocations.Datum", "Datum")
                        .WithOne("distanceToCity")
                        .HasForeignKey("TravelBridgeAPI.Models.FlightModels.FlightLocations.Distancetocity", "DatumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datum");
                });

            modelBuilder.Entity("TravelBridgeAPI.Models.FlightModels.FlightLocations.Datum", b =>
                {
                    b.Navigation("distanceToCity");
                });

            modelBuilder.Entity("TravelBridgeAPI.Models.FlightModels.FlightLocations.Rootobject", b =>
                {
                    b.Navigation("data");
                });
#pragma warning restore 612, 618
        }
    }
}
